### ISSUE TITLE
Error occurred while executing task InstallPlugin

### ISSUE THREAD

**Issue by sebenik** [youegraillot/lidarr-on-steroids#43]
**Describe the bug**
Error while installing deemix lidar plugin, thus deemix is not imported as downloader nor as indexer.

**System info (please complete the following information):**
 - OS: unraid
 - Container engine: docker

**Logs**
```
LIDARR SETUP
----------------------------------------------------------------------
PluginSource=https://github.com/ta264/Lidarr.Plugin.Deemix
----------------------------------------------------------------------

[autoconfig] Waiting Lidarr to launch on 8686...
2023-02-17T21:22:34.045Z [info] Listening on 0.0.0.0:6595
[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr.dll - Version 1.1.3.2971 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
/
[autoconfig] Installing / Updating Deemix plugin
2023-02-17T21:22:35.387Z [info] Currently running deemix-gui version 2022.12.22-r222.5d447b6035
2023-02-17T21:22:35.387Z [info] deemix-lib version 3.6.14
[Info] RootFolderWatchingService: Watching directory /music/media/music/ 
{
  "name": "InstallPlugin",
  "commandName": "Install Plugin",
  "body": {
    "githubUrl": "https://github.com/ta264/Lidarr.Plugin.Deemix",
    "sendUpdatesToClient": true,
    "isExclusive": true,
    "updateScheduledTask": true,
    "requiresDiskAccess": false,
    "isTypeExclusive": false,
    "isLongRunning": false,
    "name": "InstallPlugin",
    "trigger": "manual",
    "suppressMessages": false
  },
  "priority": "normal",
  "status": "started",
  "queued": "2023-02-17T21:22:35Z",
  "started": "2023-02-17T21:22:35Z",
  "trigger": "manual",
  "stateChangeTime": "2023-02-17T21:22:35Z",
  "sendUpdatesToClient": true,
  "updateScheduledTask": true,
  "id": 69
}[Error] CommandExecutor: Error occurred while executing task InstallPlugin 

[v1.1.3.2971] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 110
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 281
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 287
   at NzbDrone.Core.Plugins.PluginService.GetRemotePlugin(String repoUrl) in D:\a\1\s\src\NzbDrone.Core\Plugins\PluginService.cs:line 58
   at NzbDrone.Core.Plugins.InstallPluginService.Execute(InstallPluginCommand message) in D:\a\1\s\src\NzbDrone.Core\Plugins\InstallPluginService.cs:line 51
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 83
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


[Error] ServerSideNotificationService: Failed to retrieve server notifications 

[v1.1.3.2971] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 110
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.HealthCheck.ServerSideNotificationService.RetrieveServerChecks() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\ServerSideNotificationService.cs:line 61
```

**Comment by SickProdigy** [comment]
Try fresh install. I got this after over running a corrupt database.

**Comment by youegraillot** [comment]
should be fixed with latest update
