### ISSUE TITLE
Unable to login to Deemix

### ISSUE THREAD

**Issue by lasagnacrab** [youegraillot/lidarr-on-steroids#74]
**Describe the bug**
Unable to login to Deemix via the GUI. Separately, I receive a "Unable to connect to indexer, check the log for more details" error when editing connection details for Deemix indexer in the Lidarr settings.

**To Reproduce**
1. Logged out to Deemix during troubleshoot previous Deemix indexer error fixed by #65.
2. Pulled down latest container with Deemix fix (v1.5).
3. Attempt to login to Deemix with ARL via web UI.
4. Receive spinning blue circle and "Logging in..." as well as error spams in logs. 

**Expected behavior**
Successful login to Deemix

**System info (please complete the following information):**
 - OS: Unraid
 - Container engine: Docker
 - deemix-gui version 2023.9.10-r222.5d447b6035
- deemix-lib version 3.6.14
- Lidarr - Version 1.4.1.3564

**docker-compose.yml (please complete the following information):**
I don't believe I've changed anything from default, other than ports and additional paths.
![image](https://github.com/youegraillot/lidarr-on-steroids/assets/67978700/e87f5d9a-57b0-430d-b78e-242f435f3167)

**Additional context**
Logs attached. What I feel like is the relevant section pasted below which occurs when I hit login in the Deemix GUI. Deemix connection errors and AT&T errors seem odd to me. Could there be an ISP issue?

Thanks for the help.

```
2023-09-11T19:35:41.636Z [[31merror[39m] deezer.getUserData undefined:: ParseError: Unexpected token < in JSON at position 0 in "https://myattwg.att.com/olam/jsp/login/uverse/VS/UverseAccount.html"
GWAPIError: deezer.getUserData undefined:: ParseError: Unexpected token < in JSON at position 0 in "https://myattwg.att.com/olam/jsp/login/uverse/VS/UverseAccount.html"
at GW.api_call (/snapshot/deemix-gui/server/dist/app.js)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Deezer.login_via_arl (/snapshot/deemix-gui/server/dist/app.js)

[Warn] IndexerRepository: Skipping provider of unknown type RarbgSettings
[ERROR] deezer.gw deezer.getUserData undefined RequestError read ECONNRESET
[ERROR] deezer.gw deezer.getUserData undefined RequestError read ECONNRESET
[ERROR] deezer.gw deezer.getUserData undefined RequestError read ECONNRESET
[ERROR] deezer.gw deezer.getUserData undefined RequestError read ECONNRESET
[ERROR] deezer.gw deezer.getUserData undefined RequestError read ECONNRESET
[ERROR] deezer.gw deezer.getUserData undefined ParseError Unexpected token < in JSON at position 0 in "https://myattwg.att.com/olam/jsp/login/uverse/VS/UverseAccount.html"
2023-09-11T19:39:45.536Z [[31merror[39m] deezer.getUserData undefined:: ParseError: Unexpected token < in JSON at position 0 in "https://myattwg.att.com/olam/jsp/login/uverse/VS/UverseAccount.html"
GWAPIError: deezer.getUserData undefined:: ParseError: Unexpected token < in JSON at position 0 in "https://myattwg.att.com/olam/jsp/login/uverse/VS/UverseAccount.html"
at GW.api_call (/snapshot/deemix-gui/server/dist/app.js)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Deezer.login_via_arl (/snapshot/deemix-gui/server/dist/app.js)

[Warn] Deemix: Unable to connect to indexer

[v1.4.1.3564] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to authenticate with Deemix
at NzbDrone.Core.Download.Clients.Deemix.DeemixProxy.Authenticate(String baseUrl, String arl)
at NzbDrone.Core.Indexers.Deemix.Deemix.GetParser()
at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Lidarr.Core/Indexers/HttpIndexerBase.cs:line 315


[Warn] IndexerRepository: Skipping provider of unknown type RarbgSettings
[Warn] LidarrErrorPipeline: FluentValidation.ValidationException: Validation failed:
-- : Unable to connect to indexer, check the log for more details

[v1.4.1.3564] FluentValidation.ValidationException: Validation failed:
```
[lidarr.txt](https://github.com/youegraillot/lidarr-on-steroids/files/12579857/lidarr.txt)
[lidarr.0.txt](https://github.com/youegraillot/lidarr-on-steroids/files/12579858/lidarr.0.txt)
[2023-09-11-14.28.58.log](https://github.com/youegraillot/lidarr-on-steroids/files/12579859/2023-09-11-14.28.58.log)

**Comment by lasagnacrab** [comment]
Not sure what changed, but I tried logging in again this morning and everything is connecting and working correctly now. No errors in logs either. I must have re-pulled down the latest container a dozen times over the last couple days so I don't think it could have been that. I'm going to chalk it up to a network error that seems to have solved itself.
